#!/usr/bin/env zsh


_source_all_files_in () {
	CURRENT_DIR=${DOTFILES_HOME}/$1

	for file in `find "$CURRENT_DIR" -type f`; do
		source $file
	done
}

load () {
	for dir in 'alias' 'completion' 'colors' 'tools' 'private'; do
		_source_all_files_in $dir
	done

	cp ${DOTFILES_HOME}/external/.gitconfig ~/
}

