#!/usr/bin/env bash

BASH_PROFILE="$HOME/.bash_profile"

_source_all_files_in () {
	CURRENT_DIR=${DOTFILES_HOME}/$1

	for file in `find "$CURRENT_DIR" -type f`; do
		source $file	
	done
}

load () {
	for dir in 'alias' 'completion' 'colors' 'tools'; do
		_source_all_files_in $dir
	done
}

